<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // Basic Personal Information
            [
                'code' => 'nama_lengkap',
                'label' => 'NAMA LENGKAP',
                'placeholder' => 'Masukkan nama lengkap',
                'description' => 'Isi nama lengkap sesuai yang tertera di KTP dengan HURUF KAPITAL',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Nama lengkap wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Nama lengkap harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '255', 'message' => 'Nama lengkap maksimal 255 karakter'],
                ],
                'display_order' => 1,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'jenis_kelamin',
                'label' => 'JENIS KELAMIN',
                'placeholder' => 'Pilih jenis kelamin',
                'description' => 'Pilih jenis kelamin sesuai yang tertera di KTP',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'L', 'label' => 'LAKI-LAKI'],
                    ['value' => 'P', 'label' => 'PEREMPUAN'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Jenis kelamin wajib dipilih'],
                    ['rule' => 'in', 'value' => 'L,P', 'message' => 'Pilih jenis kelamin yang tersedia'],
                ],
                'display_order' => 2,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'tempat_lahir',
                'label' => 'TEMPAT LAHIR',
                'placeholder' => 'Masukkan tempat lahir',
                'description' => 'Isi tempat lahir sesuai yang tertera di KTP dengan HURUF KAPITAL',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Tempat lahir wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Tempat lahir harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '255', 'message' => 'Tempat lahir maksimal 255 karakter'],
                ],
                'display_order' => 3,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'tanggal_lahir',
                'label' => 'TANGGAL LAHIR',
                'placeholder' => 'Pilih tanggal lahir',
                'description' => 'Pilih tanggal lahir sesuai yang tertera di KTP',
                'type' => Question::TYPE_DATE,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Tanggal lahir wajib diisi'],
                    ['rule' => 'date', 'value' => '', 'message' => 'Format tanggal tidak valid'],
                    ['rule' => 'before', 'value' => 'today', 'message' => 'Tanggal lahir harus sebelum hari ini'],
                ],
                'display_order' => 4,
                'required' => true,
                'icon' => 'IconCalendar',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'usia',
                'label' => 'USIA',
                'placeholder' => 'Otomatis terisi',
                'description' => 'Usia otomatis terhitung berdasarkan tanggal lahir',
                'type' => Question::TYPE_NUMBER,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Usia wajib diisi'],
                    ['rule' => 'integer', 'value' => '', 'message' => 'Usia harus berupa angka'],
                    ['rule' => 'min_value', 'value' => '17', 'message' => 'Usia minimal 17 tahun'],
                    ['rule' => 'max_value', 'value' => '65', 'message' => 'Usia maksimal 65 tahun'],
                ],
                'display_order' => 5,
                'required' => true,
                'readonly' => true,
                'disabled' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'daerah_lahir',
                'label' => 'DAERAH LAHIR',
                'placeholder' => 'Pilih daerah lahir',
                'description' => 'Daerah asal lokasi kelahiran sesuai dengan provinsi tempat lahir',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    ['value' => 'sumatera', 'label' => 'SUMATERA'],
                    ['value' => 'jawa', 'label' => 'JAWA'],
                    ['value' => 'kalimantan', 'label' => 'KALIMANTAN'],
                    ['value' => 'bali', 'label' => 'BALI'],
                    ['value' => 'ntb', 'label' => 'NTB'],
                    ['value' => 'ntt', 'label' => 'NTT'],
                    ['value' => 'sulawesi', 'label' => 'SULAWESI'],
                    ['value' => 'maluku', 'label' => 'MALUKU'],
                    ['value' => 'papua', 'label' => 'PAPUA'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Daerah lahir wajib dipilih'],
                    ['rule' => 'in', 'value' => 'sumatera,jawa,kalimantan,bali,ntb,ntt,sulawesi,maluku,papua', 'message' => 'Pilih daerah lahir yang tersedia'],
                ],
                'display_order' => 6,
                'required' => true,
                'icon' => 'IconMapPin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'provinsi_lahir',
                'label' => 'PROVINSI LAHIR',
                'placeholder' => 'Pilih provinsi lahir',
                'description' => 'Provinsi tempat kelahiran anda',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    ['value' => 'aceh', 'label' => 'ACEH'],
                    ['value' => 'sumatera-utara', 'label' => 'SUMATERA UTARA'],
                    ['value' => 'sumatera-barat', 'label' => 'SUMATERA BARAT'],
                    ['value' => 'riau', 'label' => 'RIAU'],
                    ['value' => 'kepulauan-riau', 'label' => 'KEPULAUAN RIAU'],
                    ['value' => 'jambi', 'label' => 'JAMBI'],
                    ['value' => 'sumatera-selatan', 'label' => 'SUMATERA SELATAN'],
                    ['value' => 'kepulauan-bangka-belitung', 'label' => 'KEPULAUAN BANGKA BELITUNG'],
                    ['value' => 'bengkulu', 'label' => 'BENGKULU'],
                    ['value' => 'lampung', 'label' => 'LAMPUNG'],
                    ['value' => 'dki-jakarta', 'label' => 'DKI JAKARTA'],
                    ['value' => 'jawa-barat', 'label' => 'JAWA BARAT'],
                    ['value' => 'banten', 'label' => 'BANTEN'],
                    ['value' => 'jawa-tengah', 'label' => 'JAWA TENGAH'],
                    ['value' => 'di-yogyakarta', 'label' => 'DI YOGYAKARTA'],
                    ['value' => 'jawa-timur', 'label' => 'JAWA TIMUR'],
                    ['value' => 'bali', 'label' => 'BALI'],
                    ['value' => 'nusa-tenggara-barat', 'label' => 'NUSA TENGGARA BARAT'],
                    ['value' => 'nusa-tenggara-timur', 'label' => 'NUSA TENGGARA TIMUR'],
                    ['value' => 'kalimantan-barat', 'label' => 'KALIMANTAN BARAT'],
                    ['value' => 'kalimantan-tengah', 'label' => 'KALIMANTAN TENGAH'],
                    ['value' => 'kalimantan-selatan', 'label' => 'KALIMANTAN SELATAN'],
                    ['value' => 'kalimantan-timur', 'label' => 'KALIMANTAN TIMUR'],
                    ['value' => 'kalimantan-utara', 'label' => 'KALIMANTAN UTARA'],
                    ['value' => 'sulawesi-utara', 'label' => 'SULAWESI UTARA'],
                    ['value' => 'sulawesi-tengah', 'label' => 'SULAWESI TENGAH'],
                    ['value' => 'sulawesi-selatan', 'label' => 'SULAWESI SELATAN'],
                    ['value' => 'sulawesi-tenggara', 'label' => 'SULAWESI TENGGARA'],
                    ['value' => 'gorontalo', 'label' => 'GORONTALO'],
                    ['value' => 'sulawesi-barat', 'label' => 'SULAWESI BARAT'],
                    ['value' => 'maluku', 'label' => 'MALUKU'],
                    ['value' => 'maluku-utara', 'label' => 'MALUKU UTARA'],
                    ['value' => 'papua', 'label' => 'PAPUA'],
                    ['value' => 'papua-barat', 'label' => 'PAPUA BARAT'],
                    ['value' => 'papua-selatan', 'label' => 'PAPUA SELATAN'],
                    ['value' => 'papua-tengah', 'label' => 'PAPUA TENGAH'],
                    ['value' => 'papua-pegunungan', 'label' => 'PAPUA PEGUNUNGAN'],
                    ['value' => 'papua-barat-daya', 'label' => 'PAPUA BARAT DAYA'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Provinsi lahir wajib dipilih'],
                    ['rule' => 'in', 'value' => 'aceh,sumatera-utara,sumatera-barat,riau,kepulauan-riau,jambi,sumatera-selatan,kepulauan-bangka-belitung,bengkulu,lampung,dki-jakarta,jawa-barat,banten,jawa-tengah,di-yogyakarta,jawa-timur,bali,nusa-tenggara-barat,nusa-tenggara-timur,kalimantan-barat,kalimantan-tengah,kalimantan-selatan,kalimantan-timur,kalimantan-utara,sulawesi-utara,sulawesi-tengah,sulawesi-selatan,sulawesi-tenggara,gorontalo,sulawesi-barat,maluku,maluku-utara,papua,papua-barat,papua-selatan,papua-tengah,papua-pegunungan,papua-barat-daya', 'message' => 'Pilih provinsi lahir yang tersedia'],
                ],
                'display_order' => 7,
                'required' => true,
                'icon' => 'IconMapPin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'tinggi_badan',
                'label' => 'TINGGI BADAN (CM)',
                'placeholder' => 'Masukkan tinggi badan',
                'description' => 'Masukkan tinggi badan dalam satuan centimeter (140-220 cm)',
                'type' => Question::TYPE_NUMBER,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Tinggi badan wajib diisi'],
                    ['rule' => 'integer', 'value' => '', 'message' => 'Tinggi badan harus berupa angka'],
                    ['rule' => 'min_value', 'value' => '140', 'message' => 'Tinggi badan minimal 140 cm'],
                    ['rule' => 'max_value', 'value' => '220', 'message' => 'Tinggi badan maksimal 220 cm'],
                ],
                'display_order' => 8,
                'required' => true,
                'icon' => 'IconRuler',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'berat_badan',
                'label' => 'BERAT BADAN (KG)',
                'placeholder' => 'Masukkan berat badan',
                'description' => 'Masukkan berat badan dalam satuan kilogram (40-150 kg)',
                'type' => Question::TYPE_NUMBER,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Berat badan wajib diisi'],
                    ['rule' => 'integer', 'value' => '', 'message' => 'Berat badan harus berupa angka'],
                    ['rule' => 'min_value', 'value' => '40', 'message' => 'Berat badan minimal 40 kg'],
                    ['rule' => 'max_value', 'value' => '150', 'message' => 'Berat badan maksimal 150 kg'],
                ],
                'display_order' => 9,
                'required' => true,
                'icon' => 'IconWeight',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'nik',
                'label' => 'NIK',
                'placeholder' => 'Masukkan NIK',
                'description' => 'Nomor Induk Kependudukan sesuai yang tertera di KTP (16 digit)',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'NIK wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'NIK harus berupa teks'],
                    ['rule' => 'size', 'value' => '16', 'message' => 'NIK harus 16 digit'],
                    ['rule' => 'regex', 'value' => '/^[0-9]{16}$/', 'message' => 'NIK harus berupa 16 digit angka'],
                ],
                'display_order' => 10,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'daerah_domisili',
                'label' => 'DAERAH DOMISILI',
                'placeholder' => 'Pilih daerah domisili',
                'description' => 'Daerah tempat tinggal saat ini sesuai dengan domisili aktual',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    ['value' => 'sumatera', 'label' => 'SUMATERA'],
                    ['value' => 'jawa', 'label' => 'JAWA'],
                    ['value' => 'kalimantan', 'label' => 'KALIMANTAN'],
                    ['value' => 'bali', 'label' => 'BALI'],
                    ['value' => 'ntb', 'label' => 'NTB'],
                    ['value' => 'ntt', 'label' => 'NTT'],
                    ['value' => 'sulawesi', 'label' => 'SULAWESI'],
                    ['value' => 'maluku', 'label' => 'MALUKU'],
                    ['value' => 'papua', 'label' => 'PAPUA'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Daerah domisili wajib dipilih'],
                    ['rule' => 'in', 'value' => 'sumatera,jawa,kalimantan,bali,ntb,ntt,sulawesi,maluku,papua', 'message' => 'Pilih daerah domisili yang tersedia'],
                ],
                'display_order' => 11,
                'required' => true,
                'icon' => 'IconMapPin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'provinsi_domisili',
                'label' => 'PROVINSI DOMISILI',
                'placeholder' => 'Pilih provinsi domisili',
                'description' => 'Provinsi tempat tinggal saat ini sesuai dengan domisili aktual',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    ['value' => 'aceh', 'label' => 'ACEH'],
                    ['value' => 'sumatera-utara', 'label' => 'SUMATERA UTARA'],
                    ['value' => 'sumatera-barat', 'label' => 'SUMATERA BARAT'],
                    ['value' => 'riau', 'label' => 'RIAU'],
                    ['value' => 'kepulauan-riau', 'label' => 'KEPULAUAN RIAU'],
                    ['value' => 'jambi', 'label' => 'JAMBI'],
                    ['value' => 'sumatera-selatan', 'label' => 'SUMATERA SELATAN'],
                    ['value' => 'kepulauan-bangka-belitung', 'label' => 'KEPULAUAN BANGKA BELITUNG'],
                    ['value' => 'bengkulu', 'label' => 'BENGKULU'],
                    ['value' => 'lampung', 'label' => 'LAMPUNG'],
                    ['value' => 'dki-jakarta', 'label' => 'DKI JAKARTA'],
                    ['value' => 'jawa-barat', 'label' => 'JAWA BARAT'],
                    ['value' => 'banten', 'label' => 'BANTEN'],
                    ['value' => 'jawa-tengah', 'label' => 'JAWA TENGAH'],
                    ['value' => 'di-yogyakarta', 'label' => 'DI YOGYAKARTA'],
                    ['value' => 'jawa-timur', 'label' => 'JAWA TIMUR'],
                    ['value' => 'bali', 'label' => 'BALI'],
                    ['value' => 'nusa-tenggara-barat', 'label' => 'NUSA TENGGARA BARAT'],
                    ['value' => 'nusa-tenggara-timur', 'label' => 'NUSA TENGGARA TIMUR'],
                    ['value' => 'kalimantan-barat', 'label' => 'KALIMANTAN BARAT'],
                    ['value' => 'kalimantan-tengah', 'label' => 'KALIMANTAN TENGAH'],
                    ['value' => 'kalimantan-selatan', 'label' => 'KALIMANTAN SELATAN'],
                    ['value' => 'kalimantan-timur', 'label' => 'KALIMANTAN TIMUR'],
                    ['value' => 'kalimantan-utara', 'label' => 'KALIMANTAN UTARA'],
                    ['value' => 'sulawesi-utara', 'label' => 'SULAWESI UTARA'],
                    ['value' => 'sulawesi-tengah', 'label' => 'SULAWESI TENGAH'],
                    ['value' => 'sulawesi-selatan', 'label' => 'SULAWESI SELATAN'],
                    ['value' => 'sulawesi-tenggara', 'label' => 'SULAWESI TENGGARA'],
                    ['value' => 'gorontalo', 'label' => 'GORONTALO'],
                    ['value' => 'sulawesi-barat', 'label' => 'SULAWESI BARAT'],
                    ['value' => 'maluku', 'label' => 'MALUKU'],
                    ['value' => 'maluku-utara', 'label' => 'MALUKU UTARA'],
                    ['value' => 'papua', 'label' => 'PAPUA'],
                    ['value' => 'papua-barat', 'label' => 'PAPUA BARAT'],
                    ['value' => 'papua-selatan', 'label' => 'PAPUA SELATAN'],
                    ['value' => 'papua-tengah', 'label' => 'PAPUA TENGAH'],
                    ['value' => 'papua-pegunungan', 'label' => 'PAPUA PEGUNUNGAN'],
                    ['value' => 'papua-barat-daya', 'label' => 'PAPUA BARAT DAYA'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Provinsi domisili wajib dipilih'],
                    ['rule' => 'in', 'value' => 'aceh,sumatera-utara,sumatera-barat,riau,kepulauan-riau,jambi,sumatera-selatan,kepulauan-bangka-belitung,bengkulu,lampung,dki-jakarta,jawa-barat,banten,jawa-tengah,di-yogyakarta,jawa-timur,bali,nusa-tenggara-barat,nusa-tenggara-timur,kalimantan-barat,kalimantan-tengah,kalimantan-selatan,kalimantan-timur,kalimantan-utara,sulawesi-utara,sulawesi-tengah,sulawesi-selatan,sulawesi-tenggara,gorontalo,sulawesi-barat,maluku,maluku-utara,papua,papua-barat,papua-selatan,papua-tengah,papua-pegunungan,papua-barat-daya', 'message' => 'Pilih provinsi domisili yang tersedia'],
                ],
                'display_order' => 12,
                'required' => true,
                'icon' => 'IconMapPin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'kota_domisili',
                'label' => 'KOTA DOMISILI',
                'placeholder' => 'Masukkan kota domisili',
                'description' => 'Kota/kabupaten tempat tinggal saat ini dengan HURUF KAPITAL',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Kota domisili wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Kota domisili harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '255', 'message' => 'Kota domisili maksimal 255 karakter'],
                ],
                'display_order' => 13,
                'required' => true,
                'icon' => 'IconMapPin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'alamat_domisili',
                'label' => 'ALAMAT DOMISILI',
                'placeholder' => 'Masukkan alamat domisili',
                'description' => 'Alamat lengkap tempat tinggal saat ini dengan HURUF KAPITAL (nama jalan, nomor rumah, RT/RW, kelurahan, kecamatan)',
                'type' => Question::TYPE_TEXTAREA,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Alamat domisili wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Alamat domisili harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '1000', 'message' => 'Alamat domisili maksimal 1000 karakter'],
                ],
                'display_order' => 14,
                'required' => true,
                'icon' => 'IconMapPin',
                'group' => 'personal_info',
                'is_active' => true,
            ],

            // Program Selection
            [
                'code' => 'program_terpilih',
                'label' => 'PROGRAM YANG DIPILIH',
                'placeholder' => 'Pilih program magang yang diminati',
                'description' => 'Pilih program magang yang diminati',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    [
                        'value' => 'pkpp-estate',
                        'label' => 'PKPP ESTATE (Pend. D3-S1 Jurusan Perkebunan, Pertanian dan turunannya)',
                    ],
                    [
                        'value' => 'pkpp-ktu',
                        'label' => 'PKPP KTU (Pend. S1 Jurusan Akuntansi & Perpajakan)',
                    ],
                    [
                        'value' => 'pkpp-mill',
                        'label' => 'PKPP MILL (Pend. S1 Jurusan Teknik Mesin, Teknik Industri dan Teknik Elektro)',
                    ],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Program yang dipilih wajib dipilih'],
                    ['rule' => 'in', 'value' => 'pkpp-estate,pkpp-ktu,pkpp-mill', 'message' => 'Pilih program yang tersedia'],
                ],
                'display_order' => 15,
                'required' => true,
                'group' => 'education_info',
                'is_active' => true,
            ],

            // Education Information (conditional on program selection)
            [
                'code' => 'jurusan_pendidikan',
                'label' => 'JURUSAN PENDIDIKAN',
                'placeholder' => 'Pilih jurusan pendidikan anda',
                'description' => 'Pilih jurusan pendidikan anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Pertanian', 'label' => 'Pertanian'],
                    ['value' => 'Perkebunan', 'label' => 'Perkebunan'],
                    ['value' => 'Agribisnis', 'label' => 'Agribisnis'],
                    ['value' => 'Agroteknologi', 'label' => 'Agroteknologi'],
                    ['value' => 'Agroekoteknologi', 'label' => 'Agroekoteknologi'],
                    ['value' => 'Akuntansi', 'label' => 'Akuntansi'],
                    ['value' => 'Perpajakan', 'label' => 'Perpajakan'],
                    ['value' => 'Teknik Mesin', 'label' => 'Teknik Mesin'],
                    ['value' => 'Teknik Industri', 'label' => 'Teknik Industri'],
                    ['value' => 'Teknik Elektro', 'label' => 'Teknik Elektro'],
                    ['value' => 'Teknik Kimia', 'label' => 'Teknik Kimia'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Jurusan pendidikan wajib dipilih'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Jurusan pendidikan harus berupa teks'],
                ],
                'display_order' => 16,
                'required' => true,
                'has_custom_other_input' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'program_terpilih',
                            'operator' => 'in',
                            'values' => ['pkpp-estate', 'pkpp-ktu', 'pkpp-mill'],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'jenjang_pendidikan',
                'label' => 'JENJANG PENDIDIKAN',
                'placeholder' => 'Pilih jenjang pendidikan anda',
                'description' => 'Pilih jenjang pendidikan anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'D3', 'label' => 'D3'],
                    ['value' => 'D4', 'label' => 'D4'],
                    ['value' => 'S1', 'label' => 'S1'],
                    ['value' => 'S2', 'label' => 'S2'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Jenjang pendidikan wajib dipilih'],
                    ['rule' => 'in', 'value' => 'D3,D4,S1,S2', 'message' => 'Pilih jenjang pendidikan yang tersedia'],
                ],
                'display_order' => 17,
                'required' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'program_terpilih',
                            'operator' => 'in',
                            'values' => ['pkpp-estate', 'pkpp-ktu', 'pkpp-mill'],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'instansi_pendidikan',
                'label' => 'INSTANSI PENDIDIKAN',
                'placeholder' => 'Masukkan instansi pendidikan',
                'description' => 'Masukkan instansi pendidikan anda',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Instansi pendidikan wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Instansi pendidikan harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '255', 'message' => 'Instansi pendidikan maksimal 255 karakter'],
                ],
                'display_order' => 18,
                'required' => true,
                'has_custom_other_input' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'program_terpilih',
                            'operator' => 'in',
                            'values' => ['pkpp-estate', 'pkpp-ktu', 'pkpp-mill'],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'nim',
                'label' => 'Nomor Induk Mahasiswa (NIM)',
                'placeholder' => 'Masukkan NIM',
                'description' => 'Masukkan NIM dari instansi pendidikan anda',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'NIM wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'NIM harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '50', 'message' => 'NIM maksimal 50 karakter'],
                ],
                'display_order' => 19,
                'required' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'status_ijazah',
                'label' => 'STATUS IJAZAH',
                'placeholder' => 'Pilih status ijazah anda',
                'description' => 'Pilih status ijazah anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Ada', 'label' => 'Ada'],
                    ['value' => 'Surat Keterangan Lulus', 'label' => 'Surat Keterangan Lulus'],
                    ['value' => 'Tidak Ada', 'label' => 'Tidak Ada'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Status ijazah wajib dipilih'],
                    ['rule' => 'in', 'value' => 'Ada,Surat Keterangan Lulus,Tidak Ada', 'message' => 'Pilih status ijazah yang tersedia'],
                ],
                'display_order' => 20,
                'required' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],

            // Contact Information
            [
                'code' => 'nomor_whatsapp',
                'label' => 'NOMOR WHATSAPP',
                'placeholder' => 'Masukkan nomor whatsapp',
                'description' => 'Isikan nomor WhatsApp aktif anda.',
                'type' => Question::TYPE_TEL,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Nomor WhatsApp wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Nomor WhatsApp harus berupa teks'],
                    ['rule' => 'regex', 'value' => '/^(\+62|62|0)[0-9]{9,13}$/', 'message' => 'Format nomor WhatsApp tidak valid'],
                ],
                'display_order' => 21,
                'required' => true,
                'group' => 'contact_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'email',
                'label' => 'EMAIL',
                'placeholder' => 'Masukkan email',
                'description' => 'Isikan email aktif anda.',
                'type' => Question::TYPE_EMAIL,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Email wajib diisi'],
                    ['rule' => 'email', 'value' => '', 'message' => 'Format email tidak valid'],
                    ['rule' => 'max_length', 'value' => '255', 'message' => 'Email maksimal 255 karakter'],
                ],
                'display_order' => 22,
                'required' => true,
                'group' => 'contact_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],

            // Additional Information
            [
                'code' => 'status_perkawinan',
                'label' => 'STATUS PERKAWINAN',
                'placeholder' => 'Pilih status perkawinan saat ini',
                'description' => 'Pilih status perkawinan saat ini',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Lajang', 'label' => 'Lajang'],
                    ['value' => 'Kawin', 'label' => 'Kawin'],
                    ['value' => 'Cerai', 'label' => 'Cerai'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Status perkawinan wajib dipilih'],
                    ['rule' => 'in', 'value' => 'Lajang,Kawin,Cerai', 'message' => 'Pilih status perkawinan yang tersedia'],
                ],
                'display_order' => 23,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'melanjutkan_pendidikan',
                'label' => 'APAKAH SAAT INI SEDANG MELANJUTKAN PENDIDIKAN?',
                'placeholder' => 'Pilih jawaban',
                'description' => 'Melanjutkan pendidikan ke Universitas / Politeknik, atau Sertifikasi Profesi lainnya.',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Ya', 'label' => 'Ya'],
                    ['value' => 'Tidak', 'label' => 'Tidak'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Jawaban wajib dipilih'],
                    ['rule' => 'in', 'value' => 'Ya,Tidak', 'message' => 'Pilih jawaban yang tersedia'],
                ],
                'display_order' => 24,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'ukuran_baju',
                'label' => 'UKURAN BAJU',
                'placeholder' => 'Pilih ukuran baju anda',
                'description' => 'Pilih ukuran baju anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'S', 'label' => 'S'],
                    ['value' => 'M', 'label' => 'M'],
                    ['value' => 'L', 'label' => 'L'],
                    ['value' => 'XL', 'label' => 'XL'],
                    ['value' => 'XXL', 'label' => 'XXL'],
                    ['value' => 'XXXL', 'label' => 'XXXL'],
                    ['value' => 'XXXXL', 'label' => 'XXXXL'],
                ],
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Ukuran baju wajib dipilih'],
                    ['rule' => 'in', 'value' => 'S,M,L,XL,XXL,XXXL,XXXXL', 'message' => 'Pilih ukuran baju yang tersedia'],
                ],
                'display_order' => 25,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'riwayat_penyakit',
                'label' => 'RIWAYAT PENYAKIT',
                'placeholder' => 'Masukkan riwayat penyakit',
                'description' => 'Tuliskan riwayat penyakit dalam yang pernah diderita. Contoh: TBC atau JANTUNG atau PATAH TULANG, dsb. Tulis SEHAT jika tidak ada riwayat penyakit dalam.',
                'type' => Question::TYPE_TEXTAREA,
                'validation_rules' => [
                    ['rule' => 'required', 'value' => '', 'message' => 'Riwayat penyakit wajib diisi'],
                    ['rule' => 'string', 'value' => '', 'message' => 'Riwayat penyakit harus berupa teks'],
                    ['rule' => 'max_length', 'value' => '1000', 'message' => 'Riwayat penyakit maksimal 1000 karakter'],
                ],
                'display_order' => 26,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'enabled' => true,
                    'operator' => 'AND',
                    'conditions' => [
                        [
                            'field' => 'instansi_pendidikan',
                            'operator' => 'not_empty',
                            'values' => [],
                        ],
                    ],
                ],
                'is_active' => true,
            ],
        ];

        foreach ($questions as $questionData) {
            Question::updateOrCreate(
                ['code' => $questionData['code']],
                $questionData
            );
        }
    }
}
