<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // Basic Personal Information
            [
                'code' => 'nama_lengkap',
                'label' => 'NAMA LENGKAP',
                'placeholder' => 'Masukkan nama lengkap',
                'description' => 'Isi nama lengkap sesuai yang tertera di KTP dengan HURUF KAPITAL',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 255],
                'display_order' => 1,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'jenis_kelamin',
                'label' => 'JENIS KELAMIN',
                'placeholder' => 'Pilih jenis kelamin',
                'description' => 'Pilih jenis kelamin sesuai yang tertera di KTP',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'L', 'label' => 'LAKI-LAKI'],
                    ['value' => 'P', 'label' => 'PEREMPUAN'],
                ],
                'validation_rules' => ['required' => true, 'in' => 'L,P'],
                'display_order' => 2,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'tempat_lahir',
                'label' => 'TEMPAT LAHIR',
                'placeholder' => 'Masukkan tempat lahir',
                'description' => 'Isi tempat lahir sesuai yang tertera di KTP dengan HURUF KAPITAL',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 255],
                'display_order' => 3,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'tanggal_lahir',
                'label' => 'TANGGAL LAHIR',
                'placeholder' => 'Pilih tanggal lahir',
                'description' => 'Pilih tanggal lahir sesuai yang tertera di KTP',
                'type' => Question::TYPE_DATE,
                'validation_rules' => ['required' => true, 'date' => true, 'before' => 'today'],
                'display_order' => 4,
                'required' => true,
                'icon' => 'calendar',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'usia',
                'label' => 'USIA',
                'placeholder' => 'Otomatis terisi',
                'description' => 'Usia otomatis terhitung berdasarkan tanggal lahir',
                'type' => Question::TYPE_NUMBER,
                'validation_rules' => ['required' => true, 'integer' => true, 'min' => 17, 'max' => 65],
                'display_order' => 5,
                'required' => true,
                'readonly' => true,
                'disabled' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'daerah_lahir',
                'label' => 'DAERAH LAHIR',
                'placeholder' => 'Pilih daerah lahir',
                'description' => 'Daerah asal lokasi kelahiran sesuai dengan provinsi tempat lahir',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    'SUMATERA',
                    'JAWA',
                    'KALIMANTAN',
                    'BALI',
                    'NTB',
                    'NTT',
                    'SULAWESI',
                    'MALUKU',
                    'PAPUA',
                ],
                'validation_rules' => ['required' => true, 'string' => true],
                'display_order' => 6,
                'required' => true,
                'icon' => 'map-pin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'provinsi_lahir',
                'label' => 'PROVINSI LAHIR',
                'placeholder' => 'Pilih provinsi lahir',
                'description' => 'Provinsi tempat kelahiran anda',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    'ACEH',
                    'SUMATERA UTARA',
                    'SUMATERA BARAT',
                    'RIAU',
                    'KEPULAUAN RIAU',
                    'JAMBI',
                    'SUMATERA SELATAN',
                    'KEPULAUAN BANGKA BELITUNG',
                    'BENGKULU',
                    'LAMPUNG',
                    'DKI JAKARTA',
                    'JAWA BARAT',
                    'BANTEN',
                    'JAWA TENGAH',
                    'DI YOGYAKARTA',
                    'JAWA TIMUR',
                    'BALI',
                    'NUSA TENGGARA BARAT',
                    'NUSA TENGGARA TIMUR',
                    'KALIMANTAN BARAT',
                    'KALIMANTAN TENGAH',
                    'KALIMANTAN SELATAN',
                    'KALIMANTAN TIMUR',
                    'KALIMANTAN UTARA',
                    'SULAWESI UTARA',
                    'SULAWESI TENGAH',
                    'SULAWESI SELATAN',
                    'SULAWESI TENGGARA',
                    'GORONTALO',
                    'SULAWESI BARAT',
                    'MALUKU',
                    'MALUKU UTARA',
                    'PAPUA',
                    'PAPUA BARAT',
                    'PAPUA SELATAN',
                    'PAPUA TENGAH',
                    'PAPUA PEGUNUNGAN',
                    'PAPUA BARAT DAYA',
                ],
                'validation_rules' => ['required' => true, 'string' => true],
                'display_order' => 7,
                'required' => true,
                'icon' => 'map-pin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'tinggi_badan',
                'label' => 'TINGGI BADAN (CM)',
                'placeholder' => 'Masukkan tinggi badan',
                'description' => 'Masukkan tinggi badan dalam satuan centimeter (140-220 cm)',
                'type' => Question::TYPE_NUMBER,
                'validation_rules' => ['required' => true, 'integer' => true, 'min' => 140, 'max' => 220],
                'display_order' => 8,
                'required' => true,
                'icon' => 'ruler',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'berat_badan',
                'label' => 'BERAT BADAN (KG)',
                'placeholder' => 'Masukkan berat badan',
                'description' => 'Masukkan berat badan dalam satuan kilogram (40-150 kg)',
                'type' => Question::TYPE_NUMBER,
                'validation_rules' => ['required' => true, 'integer' => true, 'min' => 40, 'max' => 150],
                'display_order' => 9,
                'required' => true,
                'icon' => 'weight',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'nik',
                'label' => 'NIK',
                'placeholder' => 'Masukkan NIK',
                'description' => 'Nomor Induk Kependudukan sesuai yang tertera di KTP (16 digit)',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => ['required' => true, 'string' => true, 'size' => 16, 'regex' => '/^[0-9]{16}$/'],
                'display_order' => 10,
                'required' => true,
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'daerah_domisili',
                'label' => 'DAERAH DOMISILI',
                'placeholder' => 'Pilih daerah domisili',
                'description' => 'Daerah tempat tinggal saat ini sesuai dengan domisili aktual',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    'SUMATERA',
                    'JAWA',
                    'KALIMANTAN',
                    'BALI',
                    'NTB',
                    'NTT',
                    'SULAWESI',
                    'MALUKU',
                    'PAPUA',
                ],
                'validation_rules' => ['required' => true, 'string' => true],
                'display_order' => 11,
                'required' => true,
                'icon' => 'map-pin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'provinsi_domisili',
                'label' => 'PROVINSI DOMISILI',
                'placeholder' => 'Pilih provinsi domisili',
                'description' => 'Provinsi tempat tinggal saat ini sesuai dengan domisili aktual',
                'type' => Question::TYPE_SELECT,
                'options' => [
                    'ACEH',
                    'SUMATERA UTARA',
                    'SUMATERA BARAT',
                    'RIAU',
                    'KEPULAUAN RIAU',
                    'JAMBI',
                    'SUMATERA SELATAN',
                    'KEPULAUAN BANGKA BELITUNG',
                    'BENGKULU',
                    'LAMPUNG',
                    'DKI JAKARTA',
                    'JAWA BARAT',
                    'BANTEN',
                    'JAWA TENGAH',
                    'DI YOGYAKARTA',
                    'JAWA TIMUR',
                    'BALI',
                    'NUSA TENGGARA BARAT',
                    'NUSA TENGGARA TIMUR',
                    'KALIMANTAN BARAT',
                    'KALIMANTAN TENGAH',
                    'KALIMANTAN SELATAN',
                    'KALIMANTAN TIMUR',
                    'KALIMANTAN UTARA',
                    'SULAWESI UTARA',
                    'SULAWESI TENGAH',
                    'SULAWESI SELATAN',
                    'SULAWESI TENGGARA',
                    'GORONTALO',
                    'SULAWESI BARAT',
                    'MALUKU',
                    'MALUKU UTARA',
                    'PAPUA',
                    'PAPUA BARAT',
                    'PAPUA SELATAN',
                    'PAPUA TENGAH',
                    'PAPUA PEGUNUNGAN',
                    'PAPUA BARAT DAYA',
                ],
                'validation_rules' => ['required' => true, 'string' => true],
                'display_order' => 12,
                'required' => true,
                'icon' => 'map-pin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'kota_domisili',
                'label' => 'KOTA DOMISILI',
                'placeholder' => 'Masukkan kota domisili',
                'description' => 'Kota/kabupaten tempat tinggal saat ini dengan HURUF KAPITAL',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 255],
                'display_order' => 13,
                'required' => true,
                'icon' => 'map-pin',
                'group' => 'personal_info',
                'is_active' => true,
            ],
            [
                'code' => 'alamat_domisili',
                'label' => 'ALAMAT DOMISILI',
                'placeholder' => 'Masukkan alamat domisili',
                'description' => 'Alamat lengkap tempat tinggal saat ini dengan HURUF KAPITAL (nama jalan, nomor rumah, RT/RW, kelurahan, kecamatan)',
                'type' => Question::TYPE_TEXTAREA,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 1000],
                'display_order' => 14,
                'required' => true,
                'icon' => 'map-pin',
                'group' => 'personal_info',
                'is_active' => true,
            ],

            // Program Selection
            [
                'code' => 'program_terpilih',
                'label' => 'PROGRAM YANG DIPILIH',
                'placeholder' => 'Pilih program magang yang diminati',
                'description' => 'Pilih program magang yang diminati',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    [
                        'value' => 'pkpp-estate',
                        'label' => 'PKPP ESTATE (Pend. D3-S1 Jurusan Perkebunan, Pertanian dan turunannya)',
                    ],
                    [
                        'value' => 'pkpp-ktu',
                        'label' => 'PKPP KTU (Pend. S1 Jurusan Akuntansi & Perpajakan)',
                    ],
                    [
                        'value' => 'pkpp-mill',
                        'label' => 'PKPP MILL (Pend. S1 Jurusan Teknik Mesin, Teknik Industri dan Teknik Elektro)',
                    ],
                ],
                'validation_rules' => ['required' => true, 'in' => 'pkpp-estate,pkpp-ktu,pkpp-mill'],
                'display_order' => 15,
                'required' => true,
                'group' => 'education_info',
                'is_active' => true,
            ],

            // Education Information (conditional on program selection)
            [
                'code' => 'jurusan_pendidikan',
                'label' => 'JURUSAN PENDIDIKAN',
                'placeholder' => 'Pilih jurusan pendidikan anda',
                'description' => 'Pilih jurusan pendidikan anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Pertanian', 'label' => 'Pertanian'],
                    ['value' => 'Perkebunan', 'label' => 'Perkebunan'],
                    ['value' => 'Agribisnis', 'label' => 'Agribisnis'],
                    ['value' => 'Agroteknologi', 'label' => 'Agroteknologi'],
                    ['value' => 'Agroekoteknologi', 'label' => 'Agroekoteknologi'],
                    ['value' => 'Akuntansi', 'label' => 'Akuntansi'],
                    ['value' => 'Perpajakan', 'label' => 'Perpajakan'],
                    ['value' => 'Teknik Mesin', 'label' => 'Teknik Mesin'],
                    ['value' => 'Teknik Industri', 'label' => 'Teknik Industri'],
                    ['value' => 'Teknik Elektro', 'label' => 'Teknik Elektro'],
                    ['value' => 'Teknik Kimia', 'label' => 'Teknik Kimia'],
                ],
                'validation_rules' => ['required' => true, 'string' => true],
                'display_order' => 16,
                'required' => true,
                'has_custom_other_input' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'depends_on' => 'program_terpilih',
                    'show_when' => ['pkpp-estate', 'pkpp-ktu', 'pkpp-mill'],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'jenjang_pendidikan',
                'label' => 'JENJANG PENDIDIKAN',
                'placeholder' => 'Pilih jenjang pendidikan anda',
                'description' => 'Pilih jenjang pendidikan anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'D3', 'label' => 'D3'],
                    ['value' => 'D4', 'label' => 'D4'],
                    ['value' => 'S1', 'label' => 'S1'],
                    ['value' => 'S2', 'label' => 'S2'],
                ],
                'validation_rules' => ['required' => true, 'in' => 'D3,D4,S1,S2'],
                'display_order' => 17,
                'required' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'depends_on' => 'program_terpilih',
                    'show_when' => ['pkpp-estate', 'pkpp-ktu', 'pkpp-mill'],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'instansi_pendidikan',
                'label' => 'INSTANSI PENDIDIKAN',
                'placeholder' => 'Masukkan instansi pendidikan',
                'description' => 'Masukkan instansi pendidikan anda',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 255],
                'display_order' => 18,
                'required' => true,
                'has_custom_other_input' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'depends_on' => 'program_terpilih',
                    'show_when' => ['pkpp-estate', 'pkpp-ktu', 'pkpp-mill'],
                ],
                'is_active' => true,
            ],
            [
                'code' => 'nim',
                'label' => 'Nomor Induk Mahasiswa (NIM)',
                'placeholder' => 'Masukkan NIM',
                'description' => 'Masukkan NIM dari instansi pendidikan anda',
                'type' => Question::TYPE_TEXT,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 50],
                'display_order' => 19,
                'required' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],
            [
                'code' => 'status_ijazah',
                'label' => 'STATUS IJAZAH',
                'placeholder' => 'Pilih status ijazah anda',
                'description' => 'Pilih status ijazah anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Ada', 'label' => 'Ada'],
                    ['value' => 'Surat Keterangan Lulus', 'label' => 'Surat Keterangan Lulus'],
                    ['value' => 'Tidak Ada', 'label' => 'Tidak Ada'],
                ],
                'validation_rules' => ['required' => true, 'in' => 'Ada,Surat Keterangan Lulus,Tidak Ada'],
                'display_order' => 20,
                'required' => true,
                'group' => 'education_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],

            // Contact Information
            [
                'code' => 'nomor_whatsapp',
                'label' => 'NOMOR WHATSAPP',
                'placeholder' => 'Masukkan nomor whatsapp',
                'description' => 'Isikan nomor WhatsApp aktif anda.',
                'type' => Question::TYPE_TEL,
                'validation_rules' => ['required' => true, 'string' => true, 'regex' => '/^(\+62|62|0)[0-9]{9,13}$/'],
                'display_order' => 21,
                'required' => true,
                'group' => 'contact_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],
            [
                'code' => 'email',
                'label' => 'EMAIL',
                'placeholder' => 'Masukkan email',
                'description' => 'Isikan email aktif anda.',
                'type' => Question::TYPE_EMAIL,
                'validation_rules' => ['required' => true, 'email' => true, 'max' => 255],
                'display_order' => 22,
                'required' => true,
                'group' => 'contact_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],

            // Additional Information
            [
                'code' => 'status_perkawinan',
                'label' => 'STATUS PERKAWINAN',
                'placeholder' => 'Pilih status perkawinan saat ini',
                'description' => 'Pilih status perkawinan saat ini',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Lajang', 'label' => 'Lajang'],
                    ['value' => 'Kawin', 'label' => 'Kawin'],
                    ['value' => 'Cerai', 'label' => 'Cerai'],
                ],
                'validation_rules' => ['required' => true, 'in' => 'Lajang,Kawin,Cerai'],
                'display_order' => 23,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],
            [
                'code' => 'melanjutkan_pendidikan',
                'label' => 'APAKAH SAAT INI SEDANG MELANJUTKAN PENDIDIKAN?',
                'placeholder' => 'Pilih jawaban',
                'description' => 'Melanjutkan pendidikan ke Universitas / Politeknik, atau Sertifikasi Profesi lainnya.',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'Ya', 'label' => 'Ya'],
                    ['value' => 'Tidak', 'label' => 'Tidak'],
                ],
                'validation_rules' => ['required' => true, 'in' => 'Ya,Tidak'],
                'display_order' => 24,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],
            [
                'code' => 'ukuran_baju',
                'label' => 'UKURAN BAJU',
                'placeholder' => 'Pilih ukuran baju anda',
                'description' => 'Pilih ukuran baju anda',
                'type' => Question::TYPE_RADIO,
                'options' => [
                    ['value' => 'S', 'label' => 'S'],
                    ['value' => 'M', 'label' => 'M'],
                    ['value' => 'L', 'label' => 'L'],
                    ['value' => 'XL', 'label' => 'XL'],
                    ['value' => 'XXL', 'label' => 'XXL'],
                    ['value' => 'XXXL', 'label' => 'XXXL'],
                    ['value' => 'XXXXL', 'label' => 'XXXXL'],
                ],
                'validation_rules' => ['required' => true, 'in' => 'S,M,L,XL,XXL,XXXL,XXXXL'],
                'display_order' => 25,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],
            [
                'code' => 'riwayat_penyakit',
                'label' => 'RIWAYAT PENYAKIT',
                'placeholder' => 'Masukkan riwayat penyakit',
                'description' => 'Tuliskan riwayat penyakit dalam yang pernah diderita. Contoh: TBC atau JANTUNG atau PATAH TULANG, dsb. Tulis SEHAT jika tidak ada riwayat penyakit dalam.',
                'type' => Question::TYPE_TEXTAREA,
                'validation_rules' => ['required' => true, 'string' => true, 'max' => 1000],
                'display_order' => 26,
                'required' => true,
                'group' => 'additional_info',
                'conditional_logic' => [
                    'depends_on' => 'instansi_pendidikan',
                    'show_when_not_empty' => true,
                ],
                'is_active' => true,
            ],
        ];

        foreach ($questions as $questionData) {
            Question::updateOrCreate(
                ['code' => $questionData['code']],
                $questionData
            );
        }
    }
}
