export enum APPLICANT_DATA_SCREENING_STATUS {
  PENDING = 1,
  STOP = 2,
  NOT_YET = 3,
  PROCESS = 4,
  DONE = 5,
}

export enum APPLICANT_DATA_REVIEW_STATUS {
  PENDING = 1,
  STOP = 2,
  UNREVIEWED = 3,
  REJECTED = 4,
  ACCEPTED = 5,
}

export const APPLICANT_DATA_SCREENING_STATUS_LABELS = {
  [APPLICANT_DATA_SCREENING_STATUS.PENDING]: 'Pending',
  [APPLICANT_DATA_SCREENING_STATUS.STOP]: 'Stop',
  [APPLICANT_DATA_SCREENING_STATUS.NOT_YET]: 'Not Yet',
  [APPLICANT_DATA_SCREENING_STATUS.PROCESS]: 'Process',
  [APPLICANT_DATA_SCREENING_STATUS.DONE]: 'Done',
};

export const APPLICANT_DATA_REVIEW_STATUS_LABELS = {
  [APPLICANT_DATA_REVIEW_STATUS.PENDING]: 'Pending',
  [APPLICANT_DATA_REVIEW_STATUS.STOP]: 'Stop',
  [APPLICANT_DATA_REVIEW_STATUS.UNREVIEWED]: 'Unreviewed',
  [APPLICANT_DATA_REVIEW_STATUS.REJECTED]: 'Rejected',
  [APPLICANT_DATA_REVIEW_STATUS.ACCEPTED]: 'Accepted',
};
