export const MAJORS = [
  'Administrasi Publik / Negara',
  'Agribisnis',
  'Agroekoteknologi',
  'Agroteknologi',
  'Akuntansi',
  'Antropologi Budaya',
  'Arsitektur',
  'Astronomi',
  'Bimbingan dan Konseling',
  'Biologi',
  'Bisnis',
  'Bisnis Digital',
  'Desain Interior',
  'Desain Komunikasi Visual (DKV)',
  'Desain Produk',
  'Ekonomi Pembangunan',
  'Farmasi',
  'Fisika',
  'Gizi',
  'Hubungan Internasional',
  'Ilmu Hukum',
  'Ilmu Komputer',
  'Ilmu Komputer / Teknik Informatika',
  'Ilmu Komunikasi',
  'Ilmu Pemerintahan',
  'Ilmu Perpustakaan',
  'Kedokteran',
  'Kedokteran Gigi',
  'Kehutanan',
  'Kebidanan',
  'Kesehatan Masyarakat',
  'Kimia',
  'Kriminologi',
  'Manajemen',
  'Matematika',
  'Meteorologi dan Klimatologi',
  'Pariwisata',
  'PAUD (Pendidikan Anak Usia Dini)',
  'Pemasaran',
  'Pendidikan Bahasa Indonesia',
  'Pendidikan Bahasa Inggris',
  'Pendidikan Biologi',
  'Pendidikan Fisika',
  'Pendidikan Guru Sekolah Dasar (PGSD)',
  'Pendidikan Kimia',
  'Pendidikan Matematika',
  'Perbankan dan Keuangan',
  'Perhotelan',
  'Perikanan dan Kelautan',
  'Perkebunan',
  'Perpajakan',
  'Pertanian',
  'Peternakan',
  'Psikologi',
  'Sastra Arab',
  'Sastra Indonesia',
  'Sastra Inggris',
  'Sastra Jepang',
  'Sastra Jerman',
  'Seni Musik',
  'Seni Rupa Murni',
  'Seni Tari',
  'Sosiologi',
  'Statistika',
  'Sistem Informasi',
  'Teknik Elektro',
  'Teknik Industri',
  'Teknik Informatika',
  'Teknik Kimia',
  'Teknik Lingkungan',
  'Teknik Mesin',
  'Teknik Sipil',
  'Transportasi dan Logistik',
  'Teknologi Hasil Pertanian',
];

export const MAJOR_OPTIONS = MAJORS.map((major) => ({
  value: major,
  label: major,
}));
