/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationBatchIndexRouteImport } from './routes/$location/$batch/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationBatchIndexRoute = LocationBatchIndexRouteImport.update({
  id: '/$location/$batch/',
  path: '/$location/$batch/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$location/$batch': typeof LocationBatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$location/$batch': typeof LocationBatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$location/$batch/': typeof LocationBatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$location/$batch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$location/$batch'
  id: '__root__' | '/' | '/$location/$batch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationBatchIndexRoute: typeof LocationBatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$location/$batch/': {
      id: '/$location/$batch/'
      path: '/$location/$batch'
      fullPath: '/$location/$batch'
      preLoaderRoute: typeof LocationBatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationBatchIndexRoute: LocationBatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
