name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: Production

    steps:
      # Step 1: checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # Or any other LTS version you prefer
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Step 3: Install & Build Frontend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      # Creates the .env file in the frontend directory from your GitHub secret
      - name: Create frontend .env file
        run: echo "${{ secrets.FRONTEND_ENV_FILE }}" > .env
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build:prod
        working-directory: ./frontend

      # Step 4: Prepare server folder and backup old assets
      - name: Prepare server folder
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_HOME_PROJECT }}/public
            if [ -d "assets-old" ]; then
              rm -rf assets-old
            fi
            if [ -d "assets" ]; then
              mv assets assets-old
            fi

      # Step 5: Upload frontend build to VPS
      # Only the 'assets' folder containing static files is uploaded
      - name: Upload frontend build files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/assets"
          target: "${{ secrets.SSH_HOME_PROJECT }}/public"
          strip_components: 1

      # Step 6: Deploy backend to VPS via SSH
      # Running a series of commands on the server to update and restart the backend
      - name: Deploy backend and restart server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_HOME_PROJECT }}
            echo "==> 1. Fetching and applying latest changes..."
            git fetch origin main
            git reset --hard origin/main

            echo "==> 2. Installing Composer dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "==> 3. Running database migrations..."
            php artisan migrate --force

            echo "==> Deployment completed successfully! ✅"
